# Generated by Django 5.2.3 on 2025-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuser',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='uuser',
            name='name',
        ),
        migrations.AddField(
            model_name='uuser',
            name='date',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='uuser',
            name='description',
            field=models.CharField(max_length=500, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='uuser',
            name='img',
            field=models.ImageField(null='True', upload_to='images/'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='uuser',
            name='title',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
