# Generated by Django 5.2.7 on 2025-12-20 08:19

import ecommerceapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuser',
            name='img',
            field=models.ImageField(null='True', upload_to='images/', validators=[ecommerceapp.validators.validate_image_size]),
        ),
    ]
