# Generated by Django 5.2.7 on 2025-12-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_uuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuser',
            name='img',
            field=models.ImageField(null='True', upload_to='images/'),
        ),
    ]
